alchanso/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',include('main_page.urls')),
    path('trade/',include('trade.urls', namespace='trade')),
    path('',include('main.urls')),
    path('map/',include('map.urls',namespace='map')),
    path('community/',include('community.urls',namespace='community')),
    path('consumption/',include('consumption.urls',namespace='consumption')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
]+ static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

community/yourprojectname/yourprojectname/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

consumption/urls.py
from django.urls import path
from .views import *

app_name='consumption'

urlpatterns=[
    path('search/<str:nickname>/',main_consumption,name='consumption'),
    path('consumption-detail/<int:pk>/',consumption_detail.as_view(), name='consumption-detail'),
    path('calender/',calender, name="calender"),
    path('calender-update/<int:id>/', calender_update, name='calender-update'),
    path('record-delete/<int:id>/',delete, name="record-delete"),
    path('friend/',friend, name="friend"),
    path('search-friend/',search_friend, name="search-friend"),
    path('like/<int:id>/',like, name="like"),
    path('statistic/',statistic, name='statistic'),
    path('follow/<str:nickname>/', follow, name="follow"),
    path('unfollow/<str:nickname>/', unfollow, name="unfollow"),
    
]

map/urls.py
from django.urls import path
from .views import *

app_name='map'

urlpatterns=[
    path('',map_benefit_list, name='map-benefit'),
    path('map-detail/<int:pk>/',map_detail.as_view(), name='map-detail'),
    path('benefit-detail/<int:pk>/', benefit_detail.as_view(), name='benefit-detail'),
    path('scrap-benefit/<int:id>/',benefit_scrap, name='benefit-scrap'),
    path('scrap-map/<int:id>/',map_scrap, name='map-scrap'),
    path('mypage/benefit-detail/<int:id>/',benefit_scrap_detail, name='benefit-scrap-detail'),
    path('mypage/map-detail/<int:id>/',map_scrap_detail, name='map-scrap-detail'),
    
]

consumption/models.py
from django.db import models
from users.models import User
# Create your models here.
class Record(models.Model):
    CATEGORY=[
        ('음식','음식'),
        ('생필품','생필품'),
        ('여가','여가'),
        ('교통','교통'),
        ('학습','학습'),
        ('기타','기타'),
    ]
    year=models.IntegerField(verbose_name="년")
    month=models.IntegerField(verbose_name="월")
    date=models.IntegerField(verbose_name="일")
    price=models.IntegerField(verbose_name="소비금액")
    likes=models.IntegerField(default=0)
    name=models.CharField(verbose_name="구매물품",max_length=20)
    category=models.CharField(max_length=10, choices=CATEGORY)
    purpose=models.CharField(verbose_name="목적",max_length=20)
    share=models.BooleanField(verbose_name="공개여부", default=False)
    detail=models.TextField(verbose_name="상세정보")
    writer=models.ForeignKey(User, related_name="record_writer", on_delete=models.CASCADE)
    like_user=models.ManyToManyField(User, related_name="like_user")

    def __str__(self):
        return self.name

consumption/views.py
from django.shortcuts import render, redirect, get_object_or_404
from datetime import datetime
from .models import Record
from users.models import *
from django.http import Http404
from django.views.generic import  DetailView
# Create your views here.

y = [n for n in range(2023, 1999, -1)] # 2023-부터 2000 year
m=[n for n in range(1,13)] # 1~12 month
d=[n for n in range(1,32)] # 1~31 day

# 입력받은 날짜(%m/%d/%Y)를 month, day, year로 분할 후 리턴
def parseTime(date): 
    m=date[0:2]
    d=date[3:5]
    y=date[6:10]
    return y,m,d

# 가장 많이 출현한 카테고리를 리턴, 여러개일 수 있으니 리스트로 리턴
def common_category(a,b,c,d,e,f):
    max_count=max(a, b, c, d, e)
    common_category_list=[]
    if max_count == a:
        common_category_list.append("음식")
    elif max_count == b:
        common_category_list.append("생필품")
    elif max_count == c:
        common_category_list.append("여가")
    elif max_count == d:
        common_category_list.append("교통")
    elif max_count == e:
        common_category_list.append("학습")
    elif max_count == e:
        common_category_list.append("기타")

    return common_category_list

# 금융 기록
def main_consumption(request, nickname):
    # like에서 처리한 후 다시 main_consumption으로 리다이렉트 할 때 최근에 조회했던 사용자를 조회하도록 해야 하므로 세션으로 처리함
    request.session['nickname'] = nickname
    # 조회하는 유저 확인
    user = User.objects.get(nickname=nickname)

    if request.method=="GET":
        try:
            # 세션에 입력되어 있는 값이 있는지 확인
            year=request.session['year']
            month=request.session['month']
            date=request.session['date']
        except:
            # 없다면 현재 시간으로 초기화
            today=datetime.today().strftime("%m/%d/%Y")
            year, month, date=parseTime(today)
    else:
        year=request.POST.get('year')
        month=request.POST.get('month')
        date=request.POST.get('date')
        request.session['year']=year
        request.session['month']=month
        request.session['date']=date

    records=Record.objects.filter(writer=user, year=year, month=month, date=date).order_by('category')
    category=["음식","생필품","여가","교통","학습","기타"]
    context={
        "find_y":year,
        "find_m":month,
        "find_d":date,
        "year":y,
        "month":m,
        "date":d,
        "records":records,
        "category":category,
        "nickname":nickname
    }
    return render(request, 'consumption/consumption.html', context)
        
# (알찬소 영수증) 금융 기록 조회
class consumption_detail(DetailView):
    model=Record

# 금융 기록 수정
def calender_update(request, id):
    record=get_object_or_404(Record, id=id)
    if request.method=="POST":
        full_date=request.POST.get('full_date')
        price=request.POST.get('price')
        name=request.POST.get('name')
        category=request.POST.get('category')
        purpose=request.POST.get('purpose')
        share=request.POST.get('share')
        detail=request.POST.get('detail')
        share = request.POST.get('share') == "True"
        year, month, date=parseTime(full_date)
        record.year=year
        record.month=month
        record.date=date
        record.price=price
        record.name=name
        record.category=category
        record.purpose=purpose
        record.share=share
        record.detail=detail
        record.writer=request.user
        record.save()
        return redirect('consumption:consumption', request.user.nickname)
    else:
        return render(request, 'consumption/calener_update.html',{"record":record})

# 금융 기록 작성
def calender(request):
    if request.method=="GET":
        # 기본적으로 오늘이 등록되도록 
        today=datetime.today().strftime("%m/%d/%Y")
        context={
            'today':today
        }

        return render(request, 'consumption/calender.html',context)
    # 폼에 등록되어 있는 정보 가져옴 
    else:
        full_date=request.POST.get('full_date')
        price=request.POST.get('price')
        name=request.POST.get('name')
        category=request.POST.get('category')
        purpose=request.POST.get('purpose')
        share=request.POST.get('share')
        detail=request.POST.get('detail')
        share = request.POST.get('share') == "True"
        year, month, date=parseTime(full_date)
        # Record 객체 생성 
        Record.objects.create(
            year=year,
            month=month,
            date=date,
            price=price,
            name=name,
            category=category,
            purpose=purpose,
            share=share,
            detail=detail,
            writer=request.user
        )
        return redirect('consumption:consumption', request.user.nickname)

# 금융 기록 삭제 
def delete(request, id):
    record=get_object_or_404(Record, id=id)
    record.delete()
    return redirect('consumption:consumption', request.user.nickname)

# 팔로잉한 친구 조회 
def friend(request):
    following=request.user.following.all()
    following_array=[n.following for n in following]

    context={
        "following":following_array,
    }
    return render(request, 'consumption/friend.html', context)

# 친구 조회 (닉네임 or 아이디)
def search_friend(request):
    if request.method=="POST":
        search=request.POST.get("search")
        # 친구 팔로우 해도 검색 상태가 유지되도록 세션에 넣음 
        request.session['search'] = search
        # 닉네임으로 검색 1
        users=User.objects.filter(nickname__contains=search)
        # 닉네임으로 검색해도 나오지 않으면 아이디로 검색
        if not users:
            users=User.objects.filter(username__contains=search)
    else:
        try:
            users=User.objects.filter(nickname__contains=request.session['search'])
        except:
            users=None
    # 현재 유저가 팔로잉한 유저 객체를 모두 리턴 
    following=request.user.following.all() 
    # 유저 객체 중 객체들의 username만 리턴 
    following_nickname_array=[n.following.nickname for n in following]
    context={
        "following":following_nickname_array,
        "users":users
    }
    return render(request, 'consumption/search_friend.html', context)

# 팔로우
def follow(request, nickname):
    following=User.objects.get(nickname=nickname)
    Follow.objects.create(follower=request.user, following=following)
    return redirect("consumption:search-friend")

# 언팔로우
def unfollow(request,nickname):
    unfollowing=User.objects.get(nickname=nickname)
    relation=Follow.objects.filter(follower=request.user, following=unfollowing)
    relation.delete()
    return redirect("consumption:search-friend")

# 금융기록 좋아요
def like(request, id):
    record=get_object_or_404(Record, id=id)
    # 레코드 객체의 좋아요에 사용자가 없는경우 -> 좋아요를 누르도록 처리해야 함
    if request.user not in record.like_user.all():
        record.like_user.add(request.user)
        record.likes+=1
    # 레코드 객체의 좋아요에 사용자가 있는경우 -> 좋아요를 해제하도록 처리해야 함
    else:
        record.like_user.remove(request.user)
        record.likes-=1
    record.save()
    return redirect('consumption:consumption', request.session['nickname'])

# 금융 통계
def statistic(request):
    # 날짜 검색한 경우
    if request.method=="POST":
        year=request.POST.get("year")
        month=request.POST.get("month")
    # 날짜 검색 없이 처음 get 요청인 경우 현재 달을 보여줌 
    else:
        today=datetime.today().strftime("%m/%d/%Y")
        year, month, date=parseTime(today)
        
    # 각각의 카테고리에 해당하는 Record 객체 필터링 
    total=Record.objects.filter(writer=request.user, year=year, month=month).count()
    food=Record.objects.filter(writer=request.user, category="음식", year=year, month=month)
    life=Record.objects.filter(writer=request.user, category="생필품", year=year, month=month)
    leisure=Record.objects.filter(writer=request.user, category="여가", year=year, month=month)
    transportation=Record.objects.filter(writer=request.user, category="교통", year=year, month=month)
    study=Record.objects.filter(writer=request.user, category="학습", year=year, month=month)
    etc=Record.objects.filter(writer=request.user, category="기타", year=year, month=month)
    
    total_records= Record.objects.filter(writer=request.user, year=year, month=month)
    common_category_array=common_category(food.count(),life.count(),leisure.count(),transportation.count(),study.count(),etc.count())
    
    # 통계 계산
    try:
        food_p = (food.count() / total) * 100
        life_p = (life.count() / total) * 100
        leisure_p = (leisure.count() / total) * 100
        transportation_p = (transportation.count() / total) * 100
        study_p = (study.count() / total) * 100
        etc_p = (etc.count() / total) * 100
    
    # 아무 기록도 없을 경우 
    except:
        food_p=life_p=leisure_p=transportation_p=study_p=etc_p=0
        common_category_array=[]

    # html에서 리스트로 접근하기 위해 리스트에 담음 
    value=[food_p, life_p, leisure_p, transportation_p, study_p, etc_p]
    value=','.join(map(str,value))
    context={
        "common_category":common_category_array,
        "value":value,
        "year":y,
        "month":m,
        "find_y":year,
        "find_m":month,
        "total_consumed":sum(record.price for record in total_records),
        "food_c":sum(record.price for record in food),
        "life_c":sum(record.price for record in life),
        "leisure_c":sum(record.price for record in leisure),
        "transportation_c":sum(record.price for record in transportation),
        "study_c":sum(record.price for record in study),
        "etc_c":sum(record.price for record in etc),
        
    }
    return render(request, 'consumption/statistics.html', context)

consumption/templates/consumption/consumption.html
{% extends 'base.html' %}

{% block title %}금융관리{% endblock %}

{% block content %}
    {% if nickname != request.user.nickname %}
        <a style="text-decoration:none;" href="{% url 'consumption:friend' %}">
            <button type="button" class="btn-close my-2" aria-label="Close"></button>
        </a>
        <span style="color : steelblue;">{{nickname}}</span>님의 기록입니다
    {% else %}
        {% include 'consumption/consumption_nav.html' %}
        <script>
            let nav=document.getElementById("bank");
            nav.style.fontSize="30px";
            // nav.style.color=blue;
            nav.style.color = 'steelblue';
        </script>
    {% endif %}


    <div class="row my-4">
        <div class="col-8">
            <h1>{{ find_y }}년 {{ find_m }}월 {{ find_d }}일</h1>
        </div>
        <div class="col-4">
            {% if nickname == request.user.nickname %}
                <a href="{% url 'consumption:calender' %}">
                    <button type="button" class="btn btn-primary">기록하기</button>
                </a>
            {% endif %}
        </div>
    </div>

    <form action="" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-4">
                <div class="input-group">
                    <select name="year" class="form-select" aria-label="Default select example">
                        {% for i in year %}
                            {% if i == find_y %}
                                <option selected value="{{ i }}">{{ i }}</option>
                            {% else %}
                                <option value="{{ i }}">{{ i }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-3">
                <div class="input-group">
                    <select name="month" name="category" class="form-select" aria-label="Default select example">
                        {% for i in month %}
                            <option selected value="{{ i }}">{{ i }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-3">
                <div class="input-group">
                    <select name="date" class="form-select" aria-label="Default select example">
                        {% for i in date %}
                            <option selected value="{{ i }}">{{ i }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-2">
                <button 
                 type="submit" class="btn btn-secondary"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>

    {% for c in category %}
        <div class="button-box mt-5">
            <div style="margin-bottom:10px; display:inline-block; border: 2px solid transparent; border-bottom: 2px solid powderblue; border-radius: 5px;" disabled>{{ c }}</div>
        </div>

        <div class="row">
            {% for r in records %}
                {% if nickname == request.user.nickname or r.share %}
                    {% if r.category == c %}
                        <div class="col-sm-6">
                            <div class="card mb-3">
                                <div class="card-body">
                                    <div class="row"> 
                                        <div class="col-6">
                                            <p class="card-title"><span style="background-color: aliceblue" > 구매 : {{ r.name|truncatechars:6 }}</span></p>
                                        </div>
                                        <div class="col-6">
                                            <p class="card-subtitle mb-2 text-muted" style="text-align: right;">가격 - {{ r.price |truncatechars:6}}원</p>
                                        </div>
                                        
                                    </div>
                                    <div class="row"> 
                                        <div class="col-8">
                                            <p class="card-text">{{ r.detail |truncatechars:10}}</p>
                                        </div>
                                        <div class="col-4" style="text-align: right;">
                                            {% if nickname == request.user.nickname %}
                                                공개 : 
                                                {% if r.share %}
                                                    <i style="text-align: right;" class="fas fa-check-square"></i>
                                                {% else %}
                                                    <i style="text-align: right;" class="fas fa-times"></i>                                                
                                                
                                            {% endif %}
                                        </div>
                                        
                                        <div class="row mt-3"> 
                                            <div class="col-9">
                                                {% if nickname == request.user.nickname %}
                                                    <a style="text-decoration: none;" href="{% url 'consumption:consumption-detail' pk=r.pk %}" class="card-link">view more</a>
                                                {% endif %}
                                            </div>
                                            <div class="col-3" style="text-align: right;">
                                                <span style="color: red; text-align: right;"> ♥ </span>{{ r.likes }}
                                            </div>
                                            {% else %}
                                                {% if request.user in r.like_user.all %}
                                                    <a href="{% url 'consumption:like'  r.id %}" style="color:black; text-decoration: none; text-align: right;"><span style="color: red;"> ♥ </span>{{ r.likes }}</a>
                                                {% else %}
                                                    <a href="{% url 'consumption:like' r.id %}" style="color:black; text-decoration: none; text-align: right;"><span style="color: red;"> ♡ </span>{{ r.likes }}</a>
                                                {% endif %}
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}

consumption/templates/consumption/consumption_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-nav mx-2">
        <a class="nav-link" href="{% url 'consumption:consumption' request.user.nickname %}" style="font-size: 16px;" id="bank">금융</a>
    </div>

    <div class="navbar-nav mx-2">
        <a class="nav-link" href="{% url 'consumption:friend' %}" style="font-size: 16px;" id="friend">친구</a>
    </div>

    <div class="navbar-nav mx-2">
        <a class="nav-link" href="{% url 'consumption:statistic' %}" style="font-size: 16px;" id="nav_sta">통계</a>
    </div>
</nav>

consumption/templates/consumption/my_consumption.html
{% extends 'base.html' %}

{% block title %}금융관리{% endblock %}

{% block content %}
    {% if username != request.user.username %}
        <a style="text-decoration:none;" href="{% url 'consumption:friend' %}">
            <button type="button" class="btn-close my-2" aria-label="Close"></button>
        </a>
        <span style="color : steelblue;">{{username}}</span>님의 기록입니다
    {% else %}
        {% include 'consumption/consumption_nav.html' %}
        <script>
            let nav=document.getElementById("bank");
            nav.style.fontSize="30px";
            // nav.style.color=blue;
            nav.style.color = 'steelblue';
        </script>
    {% endif %}

    <div style="position: fixed; bottom: 0; margin-left: 700px;">
        <a href="{% url 'consumption:calender' %}">
            <button type="button" class="btn btn-lg btn-primary m-5">금융 기록하기</button>
        </a>
    </div>

    <div class="row my-4">
        <div class="col-8">
            <h1>{{ find_y }}년 {{ find_m }}월 {{ find_d }}일</h1>
        </div>
        <div class="col-4">
            {% if username == request.user.username %}
                <a href="{% url 'consumption:calender' %}">
                    <button type="button" class="btn btn-primary">기록하기</button>
                </a>
            {% endif %}
        </div>
    </div>

    <form action="" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-4">
                <div class="input-group">
                    <select name="year" class="form-select" aria-label="Default select example">
                        {% for i in year %}
                            {% if i == find_y %}
                                <option selected value="{{ i }}">{{ i }}</option>
                            {% else %}
                                <option value="{{ i }}">{{ i }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-3">
                <div class="input-group">
                    <select name="month" name="category" class="form-select" aria-label="Default select example">
                        {% for i in month %}
                            <option selected value="{{ i }}">{{ i }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-3">
                <div class="input-group">
                    <select name="date" class="form-select" aria-label="Default select example">
                        {% for i in date %}
                            <option selected value="{{ i }}">{{ i }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-2">
                <button 
                 type="submit" class="btn btn-secondary"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>

    {% for c in category %}
        <div class="button-box mt-5">
            <div style="margin-bottom:10px; display:inline-block; border: 2px solid transparent; border-bottom: 2px solid powderblue; border-radius: 5px;" disabled>{{ c }}</div>
        </div>

        <div class="row">
            {% for r in records %}
                {% if username == request.user.username or r.share %}
                    {% if r.category == c %}
                        <div class="col-sm-6">
                            <div class="card mb-3">
                                <div class="card-body">
                                    <div class="row"> 
                                        <div class="col-6">
                                            <p class="card-title"><span style="background-color: aliceblue" > 구매 : {{ r.name|truncatechars:6 }}</span></p>
                                        </div>
                                        <div class="col-6">
                                            <p class="card-subtitle mb-2 text-muted">가격 - {{ r.price |truncatechars:6}}원</p>
                                        </div>
                                    </div>
                                    <div class="row"> 
                                        <div class="col-8">
                                            <p class="card-text">목적 - {{ r.purpose |truncatechars:10}}</p>
                                        </div>
                                        <div class="col-4">
                                            {% if username == request.user.username %}
                                            공개 : 
                                            
                                                {% if r.share %}
                                                <i class="fas fa-check-square"></i>
                                                {% else %}
                                                <i class="fas fa-times"></i>                                                
                                                {% endif %}
                                            
                                        </div>
                                        <div class="row mt-3"> 
                                            <div class="col-9">
                                                {% if username == request.user.username %}
                                                    <a style="text-decoration: none;" href="{% url 'consumption:consumption-detail' pk=r.pk %}" class="card-link">view more</a>
                                                {% endif %}
                                            </div>
                                            <div class="col-3">
                                                <span style="color: red;"> ♥ </span>{{ r.likes }}
                                            </div>
                                            {% else %}
                                                {% if request.user in r.like_user.all %}
                                                    <a href="{% url 'consumption:like'  r.id %}" style="color:black; text-decoration: none;"><span style="color: red;"> ♥ </span>{{ r.likes }}</a>
                                                {% else %}
                                                    <a href="{% url 'consumption:like' r.id %}" style="color:black; text-decoration: none;"><span style="color: red;"> ♡ </span>{{ r.likes }}</a>
                                                {% endif %}
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}

consumption/templates/consumption/record_detail.html
{% extends 'base.html' %}

{% block title %}알찬소 영수증{% endblock %}

{% block content %}
<div class="container-fluid card">
    <a href="{% url 'consumption:consumption' request.user.nickname %}">
        <button type="button" class="btn-close m-3" aria-label="Close"></button>
    </a>

    <strong class="mt-5"><h1>알찬소 영수증</h1></strong>
    <div class="container card-body">
        <h1 class="card-title">{{record.year}} / {{record.month}} / {{record.date}} </h1>
        <h2 class="card-text my-5">가격 : {{record.price}}</h2>
        <p class="card-text">구매 상품 : {{record.name}}</p>
        <p class="card-text">구매 목적 : {{record.purpose}}</p>
        <p class="card-text mb-5">상세 설명 : {{record.detail}}</p>
        <a href="{% url 'consumption:calender-update' record.id %}">
            <button type="button" class="btn btn-primary btn-lg">수정하기</button>
        </a>

        <button type="button" class="btn btn-primary btn-lg" id="deleteRecordBtn">삭제하기</button>

        <script>
            document.getElementById('deleteRecordBtn').addEventListener('click', function () {
                var confirmation = confirm('정말 삭제하시겠습니까?');
                
                if (confirmation) {
                    window.location.href = `{% url 'consumption:record-delete' record.id %}`;
                }
            });
        </script>

    </div>
</div>
{% endblock %}

consumption/templates/consumption/search_friend.html
{% extends 'base.html' %}
{% load static %}

{% block title %}친구 검색{% endblock %}

{% block content %}
<div class="container">
<a href="{% url 'consumption:friend' %}"><button type="button" class="btn-close mb-2" aria-label="Close"></button></a>


<div class="container">
    <form method="POST" actin="" class="d-flex">
        {% csrf_token %}
        <input  name="search" class="form-control me-2" type="search" placeholder="아이디 혹은 닉네임을 검색하세요" aria-label="Search">
        <button class="btn btn-outline-primary" type="submit">Search</button>
      </form>
</div>

<div>
    {% for u in users %}
    <div class="card my-5">
        <div class="card-body">
            <div class="row">
                <div class="col-4">
                    {% if u.profile %}
                    <img style="border-radius: 100%;" width="100px" height="100px" src="{{u.profile.url}}">
                    {% else %}
                    <img style="border-radius: 100%;" width="100px" height="100px" src="{% static 'img/person.png' %}">
                    {% endif %}
                </div>
                <div class="col-5">
                    <p style="font-size:15px">
                        NAME : {{u.nickname}}<br>
                        ID : {{u.username}}
                    </p>
                </div>
                <div class="col-3">
                    {% if u.nickname in following %}
                    <a href="{% url 'consumption:unfollow' u.nickname %}"><button type="button" class="btn btn-secondary my-3">un<br>follow</button></a>
                    {% elif request.user == u %}
                    <button type="button" class="btn btn-lg btn-secondary">본인</button>
                    {% else %}
                    <a href="{% url 'consumption:follow' u.nickname %}"><button type="button" class="btn  btn-secondary my-4">follow</button></a>
                    {% endif %}
                </div>
            </div>
        </div>
      </div>
            
    {% endfor %}
    
</div>
</div>
{% endblock %}