alchanso/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',include('main_page.urls')),
    path('trade/',include('trade.urls', namespace='trade')),
    path('',include('main.urls')),
    path('map/',include('map.urls',namespace='map')),
    path('community/',include('community.urls',namespace='community')),
    path('consumption/',include('consumption.urls',namespace='consumption')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
]+ static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

community/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'community'

urlpatterns = [
    path('',views.community_main, name="community-main"),
    path('food/',food,name='food'),
    path('delivery/', delivery, name='delivery'),
    path('create-post/',create_post,name='create-post'),
    path('delivery-post/',delivery_post, name='delivery-post'),
    path('food/<str:category>/',category_posts, name='category-posts'),
    path('delivery/<str:category_delivery>',category_delivery, name='category-delivery'),
    path('delete/<int:pk>/', delete_post, name='delete-post'),
    path('delete_delivery/<int:pk>/', delete_delivery, name='delete-delivery'),
    path('edit/<int:pk>/', views.edit_post, name='edit-post'),
    path('edit_delivery/<int:pk>', views.edit_delivery, name='edit-delivery'),
    path('search/',search,name='search'),
    path('search_delivery/',search_delivery,name='search-delivery'),
    #path('ott/',ott,name='ott'),
    path('food_detail/<int:pk>/', views.food_detail, name='food-detail'),
    path('delivery_detail/<int:pk>/', views.delivery_detail,name='delivery-detail'),
    path('comment/<int:pk>/', comment, name='comment'),
    path('comment_delivery<int:pk>/',comment_delivery,name='comment-delivery'),
    path('delete_comment/<int:pk>/',views.delete_comment,name='delete-comment'),
    path('delete_deliverycomment/<int:pk>/',views.delete_deliverycomment,name='delete-deliverycomment'),
]

community/yourprojectname/yourprojectname/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

map/urls.py
from django.urls import path
from .views import *

app_name='map'

urlpatterns=[
    path('',map_benefit_list, name='map-benefit'),
    path('map-detail/<int:pk>/',map_detail.as_view(), name='map-detail'),
    path('benefit-detail/<int:pk>/', benefit_detail.as_view(), name='benefit-detail'),
    path('scrap-benefit/<int:id>/',benefit_scrap, name='benefit-scrap'),
    path('scrap-map/<int:id>/',map_scrap, name='map-scrap'),
    path('mypage/benefit-detail/<int:id>/',benefit_scrap_detail, name='benefit-scrap-detail'),
    path('mypage/map-detail/<int:id>/',map_scrap_detail, name='map-scrap-detail'),
    
]

community/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model


class Comment(models.Model):
    post=models.ForeignKey('community.Post', on_delete=models.CASCADE, related_name='comments')
    author=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="comment_author")
    text=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.text

class CommentDelivery(models.Model):
    post=models.ForeignKey('community.Delivery', on_delete=models.CASCADE, related_name='comments_delivery')
    author=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="comment_delivery")
    text=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.text

class Post(models.Model):
    CATEGORY_CHOICES=[
        ('food','Food'),
        ('delivery','Delivery'),
    ]

    title = models.CharField(max_length=30)
    author=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='food_posts', null=True, blank=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    head_image = models.ImageField(upload_to='community/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='community/files/%Y/%m/%d/', blank=True)
    category=models.CharField(max_length=20, choices=CATEGORY_CHOICES, default='food')
    community=models.CharField(max_length=20)
    def __str__(self):
        return f'[{self.pk}]{self.title}'
    def get_absolute_url(self):
        return f'/community/{self.pk}/'


class Delivery(models.Model):
    CATEGORY_CHOICES=[
        ('daily','Daily'),
        ('ott','OTT'),
    ]

    title = models.CharField(max_length=30)
    author=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='delivery_posts', null=True, blank=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    head_image = models.ImageField(upload_to='community/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='community/files/%Y/%m/%d/', blank=True)
    category_delivery=models.CharField(max_length=20, choices=CATEGORY_CHOICES, default='daily')
    community=models.CharField(max_length=20)
    def __str__(self):
        return f'[{self.pk}]{self.title}'
    def get_absolute_url(self):
        return f'/community/{self.pk}/'

community/forms.py
from django import forms
from .models import Post, Comment, Delivery, CommentDelivery

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['text']

class CommentDeliveryForm(forms.ModelForm):
    class Meta:
        model=CommentDelivery
        fields=['text']

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title', 'content','head_image','file_upload','category','author']

    def __init__(self, *args, **kwargs):
        # Get the user from the form's kwargs
        user = kwargs.pop('user', None)
        super(PostForm, self).__init__(*args, **kwargs)

        if user:
            self.fields['author'].initial = user
            self.fields['author'].widget = forms.HiddenInput()

class PostDelivery(forms.ModelForm):
    class Meta:
        model=Delivery
        fields=['title', 'content','head_image','file_upload','category_delivery','author']


    def __init__(self, *args, **kwargs):
        user=kwargs.pop('user',None)
        super(PostDelivery, self).__init__(*args, **kwargs)

        if user:
            self.fields['author'].initial = user
            self.fields['author'].widget = forms.HiddenInput()

community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment, Delivery, CommentDelivery
from .forms import PostForm, CommentForm, PostDelivery, CommentDeliveryForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def community_main(request):
    return render(request,'community/community_main.html')
def delivery(request):
    delivery_posts = Delivery.objects.all().order_by('-created_at')
    paginator = Paginator(delivery_posts, 5)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # 페이지 번호가 정수가 아닌 경우, 첫 번째 페이지를 반환합니다.
        posts = paginator.page(1)
    except EmptyPage:
        # 페이지가 비어 있는 경우, 마지막 페이지를 반환합니다.
        posts = paginator.page(paginator.num_pages)
    return render(request, 'community/delivery.html', {'posts': posts})

def food(request):
    all_posts = Post.objects.all().order_by('-created_at')
    paginator = Paginator(all_posts, 5)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # 페이지 번호가 정수가 아닌 경우, 첫 번째 페이지를 반환합니다.
        posts = paginator.page(1)
    except EmptyPage:
        # 페이지가 비어 있는 경우, 마지막 페이지를 반환합니다.
        posts = paginator.page(paginator.num_pages)
    return render(request, 'community/food.html', {'posts': posts})

def category_posts(request, category):
    posts = Post.objects.filter(category=category).order_by('-created_at')

    return render(request, 'community/category_posts.html',{'posts':posts,'category':category})

def category_delivery(request, category_delivery):
    posts = Delivery.objects.filter(category_delivery=category_delivery).order_by('-created_at')

    return render(request, 'community/category_delivery.html',{'posts':posts,'category_delivery':category_delivery})

def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            #form.instance.author = request.user
            #form.save()
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('community:food')
    else:
        form = PostForm(user=request.user)
    return render(request, 'community/create_post.html', {'form': form})

def delivery_post(request):
    if request.method == 'POST':
        delivery_form = PostDelivery(request.POST, request.FILES, user=request.user)
        if delivery_form.is_valid():
            #delivery_form.instance.author = request.user
            #delivery_form.save()
            post = delivery_form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('community:delivery')
    else:
        delivery_form = PostDelivery(user=request.user)
    return render(request, 'community/delivery_post.html', {'delivery_form': delivery_form})

def delete_post(request,pk):
    post=get_object_or_404(Post,pk=pk)

    if request.user==post.author:
        post.delete()

    return redirect('community:food')

def delete_delivery(request,pk):
    post=get_object_or_404(Delivery,pk=pk)

    if request.user==post.author:
        post.delete()

    return redirect('community:delivery')

def edit_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.user != post.author:
        return redirect('community:food-detail', pk=post.pk)

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('community:food-detail', pk=post.pk)
    else:
        form = PostForm(instance=post)

    return render(request, 'community/edit_post.html', {'form': form, 'post':post})

def edit_delivery(request, pk):
    post = get_object_or_404(Delivery, pk=pk)

    if request.user != post.author:
        return redirect('community:delivery-detail', pk=post.pk)

    if request.method == 'POST':
        delivery_form = PostDelivery(request.POST, instance=post)
        if delivery_form.is_valid():
            delivery_form.save()
            return redirect('community:delivery-detail', pk=post.pk)
    else:
        delivery_form = PostDelivery(instance=post, user=request.user)

    return render(request, 'community/edit_delivery.html', {'delivery_form': delivery_form, 'post':post})


def food_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments=Comment.objects.filter(post=post)
    return render(request, 'community/food_detail.html', {'post': post,'comments':comments})

def delivery_detail(request,pk):
    post = get_object_or_404(Delivery, pk=pk)
    comments_delivery=CommentDelivery.objects.filter(post=post)
    return render(request, 'community/delivery_detail.html',{'post': post,'comments_delivery':comments_delivery})
'''
def ott(request):
    return render(request, 'community/ott.html')
'''

def search(request):
    query=request.GET.get('q')

    if query:
        posts=Post.objects.filter(title__icontains=query)
    else:
        if query:
            posts = Post.objects.filter(content__icontains=query)
        else:
            posts = []
    return render(request,'community/search_results.html',{'posts':posts, 'query':query})

def search_delivery(request):
    query=request.GET.get('q')

    if query:
        posts=Delivery.objects.filter(title__icontains=query)
    else:
        if query:
            posts = Delivery.objects.filter(content__icontains=query)
        else:
            posts = []
    return render(request,'community/search_delivery.html',{'posts':posts, 'query':query})


def comment(request, pk):
    post=get_object_or_404(Post, pk=pk)
    comments=Comment.objects.filter(post=post)

    if request.method=='POST':
        comment_form=CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment=comment_form.save(commit=False)
            new_comment.post=post
            new_comment.author=request.user
            new_comment.save()
            return redirect('community:food-detail', pk=pk)
        else:
            comment_form=CommentForm()
        return render(request, 'community/food_detail.html',{'post': post, 'comments':comments, 'comment_form':comment_form})

def comment_delivery(request, pk):
    post=get_object_or_404(Delivery, pk=pk)
    comments_delivery=CommentDelivery.objects.filter(post=post)

    if request.method=='POST':
        comment_form=CommentDeliveryForm(request.POST)
        if comment_form.is_valid():
            new_comment=comment_form.save(commit=False)
            new_comment.post=post
            new_comment.author=request.user
            new_comment.save()
            return redirect('community:delivery-detail', pk=pk)
        else:
            comment_form = CommentDeliveryForm()

        return render(request, 'community/delivery_detail.html',{'post': post, 'comments_delivery': comments_delivery, 'comment_form': comment_form})


def delete_comment(request,pk):
    comment=get_object_or_404(Comment, pk=pk)

    if comment.author==request.user:
        comment.delete()

    return redirect('community:food-detail',pk=comment.post.pk)

def delete_deliverycomment(request,pk):
    comment=get_object_or_404(CommentDelivery, pk=pk)

    if comment.author==request.user:
        comment.delete()

    return redirect('community:delivery-detail',pk=comment.post.pk)

community/templates/community/community_main.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Welcome to the Community{% endblock %}

{% block content %}
<hr>
<br>

<div class="card mb-4" style="width: 100%;">
  <img src="{% static 'img/disney.png' %}" class="card-img-top" alt="">
  <div class="card-body">
    <h3 class="card-title">밥친구&같이 배달시켜먹어요</h3>
    <p class="card-text">점심시간 혼밥하기 싫은 사람, 배달비 아끼고 싶은 사람 여기로 들어와서 밥 같이 먹어요</p>
    <a href="{% url 'community:food' %}" class="btn btn-primary">Go Website</a>
  </div>

</div>
<div class="card mb-4" style="width: 100%;">
  <img src="{% static 'img/netflix.png' %}" class="card-img-top" alt="">
  <div class="card-body">
    <h3 class="card-title">공동구매해요</h3>
    <p class="card-text">혼자 사는데 대용량 사기 부담스러웠던 사람들, 여기 들어와서 함께 구매해요</p>
    <a href="{% url 'community:delivery' %}" class="btn btn-primary">Go Website</a>
  </div>
</div>
{% endblock %}

community/templates/community/delivery.html
{% extends 'base.html' %}
{% block title %}공동구매해요{% endblock %}
{% block content %}
<a href="{% url 'community:community-main' %}"><button type="button" class="btn-close m-2" aria-label="Close"></button></a>
<div>
<a href="{% url 'community:category-delivery' category_delivery='daily' %}"><button type="button" class="btn btn-lg btn-primary" >생필품</button></a>
<a href="{% url 'community:category-delivery' category_delivery='ott' %}"><button type="button" class="btn btn-lg btn-primary" >OTT</button></a>
</div>

<hr>

<!-- Search Widget -->
  <div class="container-fluid">
    <form class="d-flex" method="get" action="{% url 'community:search-delivery' %}">
      <input class="form-control me-2" type="text" name="q" class="form-control" placeholder="Search for...">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>

<div class="container">
  <div class="row justify-content-center">
    {% for post in posts %}
        <div class="card my-4" style="width: 30rem;">
          {% if post.head_image %}
            <img src="{{ post.head_image.url }}" class="card-img-top">
          {% else %}
            <img src=".." class="card-img-top">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text" style="font-size: 14px">{{ post.content }}</p>
            <a href="{% url 'community:delivery-detail' pk=post.pk %}" class="btn btn-primary">Read More</a>
            <!--
            <a href="{% url 'community:delivery-detail' pk=post.pk %}" class="btn btn-primary">
              <button type="submit" class="btn-btn-lg btn-primary">Read More</button>
            </a>
            -->
            <p class="text-right" style="font-size: 10px">{{ post.created_at }}</p>
          </div>
        </div>
      <hr>
    {% endfor %}
  </div>

  <div class="pagination justify-content-center">
    <ul class="pagination">
      {% if posts.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% endif %}
      {% for num in posts.paginator.page_range %}
        <li class="page-item {% if num == page_obj.number %}active{% endif %}">
          <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
      {% endfor %}
      {% if posts.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
</div>

<div id="write-button" style="position: fixed; bottom: 20px; right: 20px;">
  <a class="my-5" style="text-align:center;" href="{% url 'community:delivery-post' %}">
    <button type="submit" class="btn btn-lg btn-primary">글쓰기</button>
  </a>
</div>
</div>
{% endblock %}

community/templates/community/delivery_detail.html
{% extends 'base.html' %}
{% block title %}같이 밥 먹어요{% endblock %}

{% block content %}
<style>
    .button-container {
        position: fixed;
        bottom: 20px;
        right: 20px;
        display: flex;
        flex-direction: column;
        align-items: flex-end;
    }

    .button-container button {
        margin-top: 5px; /* 수정하기 버튼과 삭제 버튼 간격 조절 */
    }

    .button-container .btn-primary {
        padding: 8px 15px; /* 수정하기 버튼 크기 조절 */
    }

</style>
<a href="{% url 'community:delivery' %}"><button type="button" class="btn-close m-2" aria-label="Close"></button></a>
<div class="container">
  <div class="card mx-auto mt-5" style="width: 18rem;">
    {% if post.head_image %}
      <img src="{{ post.head_image.url }}" class="card-img-top">
    {% else %}
      <img src=".." class="card-img-top">
    {% endif %}
    <div class="card-body">
      <h4 class="card-title">{{ post.title }}</h4>
      <p class="card-text">{{ post.content }}</p>
      <p class="card-text" style="font-size:10px">{{ post.created_at }}</p>
      <p class="card-text" style="font-size:10px">Category: {{ post.category_delivery }}</p>
    </div>
  </div>
</div>
<hr>

<!--Comment-->
<div>
  <h3>Comment</h3>
  <br>
  <div>
  {%  for comment in comments_delivery %}
       <p>
           {{ comment.text }}-{{ comment.author }}-{{ comment.created_at }}
           {% if comment.author == user %}
           <a href="{% url 'community:delete-deliverycomment' pk=comment.pk %}">삭제</a>
           {% endif %}
       </p>
  {% endfor %}
  </div>

  <div>
  <form method="post" action="{% url 'community:comment-delivery' pk=post.pk %}">
      {% csrf_token %}
      {{ comment_form.as_p }}
      <button type="submit">댓글 남기기</button>
  </form>
  </div>
</div>


<!--Delete Post-->
<div class="button-container">
<div>
  {% if post.author == user %}
    <form method="post" id="delete-post-form" action="{% url 'community:delete-delivery' pk=post.pk %}">
        {% csrf_token %}
        <button type="button" class="btn btn-danger" onclick="confirmDelete()">게시글 삭제</button>
    </form>
  {% endif %}
</div>

<script>
  function confirmDelete() {
    var result = confirm("이 글을 삭제하시겠습니까?");

    if (result) {
      document.getElementById('delete-post-form').submit();
      console.log("완료되었습니다.");
    } else {
      console.log("취소되었습니다");
    }
  }
</script>
<!--Edit Post-->
<div>
    {% if post.author == user %}
    <a href="{% url 'community:edit-delivery' pk=post.pk %}" class="btn btn-primary text-white">수정하기</a>
    <!--
        <a href="{% url 'community:edit-delivery' pk=post.pk %}" class="btn btn-lg btn-primary">
            <button type="button" class="text-white">수정하기</button>
        </a>
        -->
    {% endif %}
</div>
</div>

{% endblock %}

community/templates/community/edit_delivery.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}같이 밥 먹어요{% endblock %}

{% block content %}
<h2>Edit Post</h2>
<form method="post" action="{% url 'community:edit-delivery' pk=post.pk %}">
    {% csrf_token %}
    <div class="input-group my-3">
        <span class="input-group-text"> 제목  </span>
        {{ delivery_form.title|add_class:"form-control" }}
        {% if delivery_form.title.errors %}
        <script>
          alert("{{ delivery_form.title.errors.as_text }}");
      </script>
        {% endif %}
    </div>
    <div class="input-group my-3">
        <span class="input-group-text"> 내용  </span>
        {{ delivery_form.content|add_class:"form-control" }}
        {% if delivery_form.content.errors %}
        <script>
          alert("{{ delivery_form.content.errors.as_text }}");
      </script>
        {% endif %}
    </div>
    <div class="input-group my-3">
        <span class="input-group-text"> 이미지 </span>
        {{ delivery_form.head_image|add_class:"form-control" }}
        {% if delivery_form.head_image.errors %}
        <script>
          alert("{{ delivery_form.head_image.errors.as_text }}");
      </script>
        {% endif %}
    </div>
    <div class="input-group my-3">
        <span class="input-group-text"> 파일업로드  </span>
        {{ delivery_form.file_upload|add_class:"form-control" }}
        {% if delivery_form.file_upload.errors %}
        <script>
          alert("{{ delivery_form.place.errors.as_text }}");
      </script>
        {% endif %}
    </div>
    <div class="input-group my-3">
        <span class="input-group-text"> 카테고리  </span>
        {{ delivery_form.category_delivery|add_class:"form-control" }}
        {% if delivery_form.category_delivery.errors %}
        <script>
          alert("{{ delivery_form.category_delivery.errors.as_text }}");
      </script>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>
{% endblock %}

community/templates/community/food.html
{% extends 'base.html' %}
{% block title %}같이 밥 먹어요{% endblock %}
{% block content %}

<a href="{% url 'community:community-main' %}"><button type="button" class="btn-close m-2" aria-label="Close"></button></a>

<div>
<a href="{% url 'community:category-posts' category='food' %}"><button type="button" class="btn btn-lg btn-primary" >혼밥 싫어</button></a>
<a href="{% url 'community:category-posts' category='delivery' %}"><button type="button" class="btn btn-lg btn-primary" >같이 배달시켜요</button></a>
</div>

<hr>

<!-- Search Widget -->

  <div class="container-fluid">
    <form class="d-flex" method="get" action="{% url 'community:search' %}">
      <input class="form-control me-2" type="text" name="q" class="form-control" placeholder="Search for...">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>

<div class="container">
  <div class="row justify-content-center">
    {% for post in posts %}
        <div class="card my-4" style="width: 30rem;">
          {% if post.head_image %}
            <img src="{{ post.head_image.url }}" class="card-img-top">
          {% else %}
            <img src=".." class="card-img-top">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text" style="font-size: 14px">{{ post.content }}</p>
            <a href="{% url 'community:food-detail' pk=post.pk %}" class="btn btn-primary">Read More</a>
            <p class="text-right" style="font-size: 10px">{{ post.created_at }}</p>
          </div>
        </div>
      <hr>
    {% endfor %}
  </div>

  <div class="pagination justify-content-center">
    <ul class="pagination">
      {% if posts.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% endif %}
      {% for num in posts.paginator.page_range %}
        <li class="page-item {% if num == posts.number %}active{% endif %}">
          <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
      {% endfor %}
      {% if posts.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ posts.paginator.num_pages }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
</div>

<div id="write-button" style="position: fixed; bottom: 20px; right: 20px;">
  <a class="my-5" style="text-align:center;" href="{% url 'community:create-post' %}">
    <button type="submit" class="btn btn-lg btn-primary">글쓰기</button>
  </a>
</div>
</div>
{% endblock %}

community/templates/community/food_detail.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}같이 밥 먹어요{% endblock %}

{% block content %}
<style>
    .button-container {
        position: fixed;
        bottom: 20px;
        right: 20px;
        display: flex;
        flex-direction: column;
        align-items: flex-end;
    }

    .button-container button {
        margin-top: 5px; /* 수정하기 버튼과 삭제 버튼 간격 조절 */
    }

    .button-container .btn-primary {
        padding: 8px 15px; /* 수정하기 버튼 크기 조절 */
    }

</style>
<a href="{% url 'community:food' %}"><button type="button" class="btn-close m-2" aria-label="Close"></button></a>

<div class="container">
  <div class="card mx-auto mt-5" style="width: 18rem;">
    {% if post.head_image %}
      <img src="{{ post.head_image.url }}" class="card-img-top">
    {% else %}
      <img src=".." class="card-img-top">
    {% endif %}
    <div class="card-body">
      <h4 class="card-title">{{ post.title }}</h4>
      <p class="card-text">{{ post.content }}</p>
      <p class="card-text" style="font-size:10px">{{ post.created_at }}</p>
      <p class="card-text" style="font-size:10px">Category: {{ post.get_category_display }}</p>
    </div>
  </div>
</div>
<hr>

<!--Comment-->
<div>
  <h3>Comment</h3>
  <br>
  <div>
  {%  for comment in comments %}
       <p>
           {{ comment.text }}-{{ comment.author }}-{{ comment.created_at }}
           {% if comment.author == user %}
           <a href="{% url 'community:delete-comment' pk=comment.pk %}">삭제</a>
           {% endif %}
       </p>
  {% endfor %}
  </div>

  <div>
  <form method="post" action="{% url 'community:comment' pk=post.pk %}">
      {% csrf_token %}
      <div class="input-group my-3">
     
        {{ comment_form.text|add_class:"form-control" }}
        {% if comment_form.text.errors %}
        <script>
          alert("{{ comment_form.text.errors.as_text }}");
      </script>
        {% endif %}
    </div>
      <button type="submit">댓글 남기기</button>
  </form>
  </div>
</div>


<!--Delete Post-->
<div class="button-container">
<div>
  {% if post.author == user %}
    <form method="post" id="delete-post-form" action="{% url 'community:delete-post' pk=post.pk %}">
        {% csrf_token %}
        <button type="button" class="btn btn-danger" onclick="confirmDelete()">게시글 삭제</button>
    </form>
  {% endif %}
</div>

<script>
  function confirmDelete() {
    var result = confirm("이 글을 삭제하시겠습니까?");

    if (result) {
      document.getElementById('delete-post-form').submit();
      console.log("완료되었습니다.");
    } else {
      console.log("취소되었습니다");
    }
  }
</script>

<!--Edit Post-->
<div>
    {% if post.author == user %}
    <a href="{% url 'community:edit-post' pk=post.pk %}" class="btn btn-primary text-white">수정하기</a>
    <!--
        <a href="{% url 'community:edit-post' pk=post.pk %}" class="btn btn-primary">
            <button type="submit" class="btn btn-lg btn-primary">수정하기</button>
        </a>
        -->
    {% endif %}
</div>
</div>

{% endblock %}