accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns=[
    path('signup/',signup_view, name='signup'),
    path('login/',login_view,name='login' ),
    path('logout/',logout_view, name='logout'),
    path('mypage/',mypage,name="mypage"),
    path('update-user-info/',update_userinfo, name='update-user-info'),
    path('my-benefit-scrap',benefit_scrap, name='benefit-scrap'),
    path('my-map-scrap',map_scrap, name='map-scrap'),
    path('my-trade',my_trade, name='my-trade'),
    path('my-trade-detail/<int:post_id>/',my_trade_detail, name='my-trade-detail'),
    path('chatroom/<int:post_id>/',seller_chat, name='seller-chat'),
    path('proceeding-chat',proceeding_chat, name='proceeding-chat'),
    path('leave-chat-room/<int:room_id>/',leave_chat_room, name='leave-chat-room'),
    path('review-list/',review_make, name='review-list'),
    path('my-post-food/',my_post_food, name='my-post-food'),
    path('my-post-ott/',my_post_ott, name='my-post-ott'),
]

alchanso/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',include('main_page.urls')),
    path('trade/',include('trade.urls', namespace='trade')),
    path('',include('main.urls')),
    path('map/',include('map.urls',namespace='map')),
    path('community/',include('community.urls',namespace='community')),
    path('consumption/',include('consumption.urls',namespace='consumption')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
]+ static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

community/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'community'

urlpatterns = [
    path('',views.community_main, name="community-main"),
    path('food/',food,name='food'),
    path('delivery/', delivery, name='delivery'),
    path('create-post/',create_post,name='create-post'),
    path('delivery-post/',delivery_post, name='delivery-post'),
    path('food/<str:category>/',category_posts, name='category-posts'),
    path('delivery/<str:category_delivery>',category_delivery, name='category-delivery'),
    path('delete/<int:pk>/', delete_post, name='delete-post'),
    path('delete_delivery/<int:pk>/', delete_delivery, name='delete-delivery'),
    path('edit/<int:pk>/', views.edit_post, name='edit-post'),
    path('edit_delivery/<int:pk>', views.edit_delivery, name='edit-delivery'),
    path('search/',search,name='search'),
    path('search_delivery/',search_delivery,name='search-delivery'),
    #path('ott/',ott,name='ott'),
    path('food_detail/<int:pk>/', views.food_detail, name='food-detail'),
    path('delivery_detail/<int:pk>/', views.delivery_detail,name='delivery-detail'),
    path('comment/<int:pk>/', comment, name='comment'),
    path('comment_delivery<int:pk>/',comment_delivery,name='comment-delivery'),
    path('delete_comment/<int:pk>/',views.delete_comment,name='delete-comment'),
    path('delete_deliverycomment/<int:pk>/',views.delete_deliverycomment,name='delete-deliverycomment'),
]

community/yourprojectname/yourprojectname/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

map/urls.py
from django.urls import path
from .views import *

app_name='map'

urlpatterns=[
    path('',map_benefit_list, name='map-benefit'),
    path('map-detail/<int:pk>/',map_detail.as_view(), name='map-detail'),
    path('benefit-detail/<int:pk>/', benefit_detail.as_view(), name='benefit-detail'),
    path('scrap-benefit/<int:id>/',benefit_scrap, name='benefit-scrap'),
    path('scrap-map/<int:id>/',map_scrap, name='map-scrap'),
    path('mypage/benefit-detail/<int:id>/',benefit_scrap_detail, name='benefit-scrap-detail'),
    path('mypage/map-detail/<int:id>/',map_scrap_detail, name='map-scrap-detail'),
    
]

trade/urls.py
from django.urls import path
from . import views

app_name='trade'

urlpatterns=[
    path('r/',views.trade_require,name='trade'),
    path('f/',views.trade_finish, name='trade-finish'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.trade_detail, name='trade_detail'),
    path('<int:pk>/edit/', views.edit_post, name='edit_post'),
    path('<int:pk>/delete/', views.delete_post, name='delete_post'),
    path('<int:post_id>/chat/<int:chatroom_id>', views.into_chatroom, name='chating'),
    path('<int:post_id>/go-chat/',views.chat, name='go-chat'),
    path('seller-chat/',views.seller_chat, name="seller-chat"),
    path('<int:pk>/chat/', views.chat, name='chat'),
    path('<int:pk>/like/', views.like_post, name='like_post'),
    path('liked/', views.liked_posts, name='liked_posts'),
    path('<int:post_id>/review/', views.create_review, name='review'),
]

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):
    profile = forms.ImageField(required=False)
    class Meta():
        model=get_user_model()
        fields=['username', 'email', 'nickname', 'profile']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from .forms import  SignUpForm
from trade.models import *
from community.models import  Delivery
from community.models import Post as CommunityPost
# 회원가입
def signup_view(request):
    if request.method == "GET":
        form = SignUpForm()
        context = {'form': form}
        return render(request, 'accounts/signup.html', context)
    form = SignUpForm(request.POST, request.FILES)
    # 유효한 내용인지 확인
    if form.is_valid():
        user = form.save()
        return redirect('main')
    else:
        return render(request, 'accounts/signup.html', {'form': form})

# 로그인
def login_view(request):
    if request.method=="GET":
        return render(request, 'accounts/login.html', {'form':AuthenticationForm})
    form=AuthenticationForm(request, data=request.POST)
    if form.is_valid():
        login(request, form.user_cache)
        return redirect('main')
    return render(request, 'accounts/login.html',{'form':form})

# 로그아웃
def logout_view(request):
    if request.user.is_authenticated:
        logout(request)

    return redirect('main')

# 마이페이지
def mypage(request):
    return render(request, 'accounts/mypage.html')

def review_make(request):
    posts=Post.objects.filter(allowed_reviewer=request.user).order_by('-id')
    return render(request, 'accounts/review_list.html',{'posts':posts})

def update_userinfo(request):
    if request.method=="POST":
        nickname=request.POST.get('nickname')
        email=request.POST.get('email')
        new_profile=request.FILES.get('profile')
        if new_profile:
            request.user.profile.delete()
            request.user.profile=new_profile
        request.user.nickname=nickname
        request.user.email=email
        request.user.save()
        return redirect('accounts:mypage')
    return render(request, 'accounts/update_userinfo.html')

def benefit_scrap(request):
    benefits=request.user.scrap_benefits.all()
    context = {
        'benefits': benefits
    }
    return render(request, 'accounts/benefit_scrap.html', context)

def map_scrap(request):
    maps=request.user.map_benefits.all()
    context={
        'maps':maps
    }
    return render(request, 'accounts/map_scrap.html', context)

# 내가 올린 중고거래
def my_trade(request):
    trades=Post.objects.filter(author=request.user)
    context={
        'trades':trades
    }
    return render(request, 'accounts/my_trade.html',context)

def my_trade_detail(request, post_id):
    post=get_object_or_404(Post, id=post_id)
    context={
        'post':post
    }
    return render(request, 'accounts/trade_detail.html',context)

# 해당하는 중고거래에서 생긴 채팅방 조회
def seller_chat(request, post_id):
    chat_room=ChatRoom.objects.filter(post=post_id, seller=request.user)
    return render(request, 'accounts/seller_chat.html',{'chat_room':chat_room})

# 진행중인 채팅방 
def proceeding_chat(request):
    chat_room=ChatRoom.objects.filter( buyer=request.user)
    return render(request,'accounts/buyer_chat.html',{'chat_room':chat_room} )

# 채팅 나가기
def leave_chat_room(request, room_id):
    chat_room=ChatRoom.objects.filter(id=room_id)
    chat_room.delete()
    return redirect('accounts:proceeding-chat')

# 커뮤니티 음식
def my_post_food(request):
    posts=CommunityPost.objects.filter( author=request.user).order_by('-id')
    return render(request, 'accounts/my_food.html',{'posts':posts})

# 커뮤니티 ott
def my_post_ott(request):
    posts=Delivery.objects.filter( author=request.user).order_by('-id')
    return render(request, 'accounts/my_ott.html',{'posts':posts})

accounts/templates/accounts/benefit_scrap.html
{% extends 'base.html' %}


{% block title %}여기에 제목을 써주세요{% endblock %}

{% block content %}
{% include 'accounts/map_nav.html' %}
<script>
    let nav=document.getElementById("benefit");
    nav.style.fontSize="30px";
    // nav.style.color=blue;
    nav.style.color = 'steelblue';
</script>

<div class="row">
    {% for b in benefits %}
  <div class="col-sm-6 my-3">
    <div class="card">
      <div class="card-body">
        <div class="row">
            <div class="col-7">
                <h1 class="card-title">{{b.title}}
                    
                </h1>
            </div>
            <div class="col-5">
                <p>D-day  {{b.remaining_days}}</p>
            </div>
        </div>
        <p class="card-text">{{b.introduction}}</p>
        <div class="row">
            <div class="col-7">
        <a href="{% url 'map:benefit-scrap-detail' id=b.pk %}" class="btn btn-outline-dart btn-block btn-sm btn-primary">view more</a>
    </div>
    <div style="font-size:20px; color:steelblue; text-decoration:none;"  class="col-5">


</div>
</div>

      </div>
    </div>
    {% endfor %}
  </div>

{% endblock %}

accounts/templates/accounts/buyer_chat.html
{% extends 'base.html' %}


{% block title %}구매자 채팅방{% endblock %}

{% block content %}
<a href="{% url 'accounts:mypage' %}"><button type="button" class="btn-close m-2" aria-label="Close"></button></a>

{% for c in chat_room %}

<div class="card mb-3">
    <a style="text-decoration: none" href="{% url 'trade:chating' c.post.id  c.id %}">
    <div style="color:black" class="card-body">
        사려는 물건-{{c.post.title}}<br>
        판매자 - {{c.seller.nickname}}</a>
    </div>
    <a style="text-decoration: none" href="{% url 'accounts:leave-chat-room' c.id %}">
        <button style="color:black" type="button" class="btn btn-outline-primary m-3">채팅방 나가기</button>
    </a>
  </div>
  

{% endfor %}



{% endblock %}

accounts/templates/accounts/community_nav.html
<nav class="mx-5 navbar navbar-expand-lg navbar-light bg-light">

    <div class=" navbar-nav">
        <a class="nav-link" href="{% url 'accounts:my-post-food' %}" style="font-size: 16px;" id="food">음식</a>
    </div>

    <div class="navbar-nav mx-2">
        <a class="nav-link" href="{% url 'accounts:my-post-ott' %}" style="font-size: 16px;" id="ott">OTT</a>
    </div>
</nav>

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}로그인{% endblock %}

{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <div class="input-group my-3">
            <span  class="input-group-text"> 아이디  </span>
            {{ form.username|add_class:"form-control" }}
            {% if form.username.errors %}
            <script>
                alert("{{ form.username.errors.as_text }}");
            </script>
            {% endif %}
        </div>

        <div class="input-group my-3">
            <span  class="input-group-text"> 비밀번호   </span>
            {{ form.password|add_class:"form-control" }}
            {% if form.password.errors %}
            <script>
                alert("{{ form.password.errors.as_text }}");
            </script>
            {% endif %}
          </div>
    </div>
    <div class="my-5" style="text-align: center;">
        <button type="submit" class="btn btn-lg btn-primary">로그인</button>
    </div>
    <div style="text-align: center;">
        계정이 없으신가요?<br>
        <a href="{% url 'accounts:signup' %}">회원가입</a>하러가기
    </div>
</form>
{% endblock %}

accounts/templates/accounts/map_nav.html
<nav class="mx-5 navbar navbar-expand-lg navbar-light bg-light">

    <div class=" navbar-nav">
        <a class="nav-link" href="{% url 'accounts:map-scrap' %}" style="font-size: 16px;" id="map">방문 혜택</a>
    </div>

    <div class="navbar-nav mx-2">
        <a class="nav-link" href="{% url 'accounts:benefit-scrap' %}" style="font-size: 16px;" id="benefit">구독 혜택</a>
    </div>
</nav>

accounts/templates/accounts/map_scrap.html
{% extends 'base.html' %}


{% block title %}여기에 제목을 써주세요{% endblock %}

{% block content %}
{% include 'accounts/map_nav.html' %}
<script>
    let nav=document.getElementById("map");
    nav.style.fontSize="30px";
    // nav.style.color=blue;
    nav.style.color = 'steelblue';
</script>
<div class="row">
    {% for m in maps %}
  <div class="col-sm-6 my-3">
    <div class="card">
      <div class="card-body">
        <div class="row">
            <div class="col-7">
                <h1 class="card-title">{{m.title}}
                    
                </h1>
            </div>
            <div class="col-5">
                <p>D-day  {{m.remaining_days}}</p>
            </div>
        </div>
        <p class="card-text">{{m.introduction}}</p>
        <div class="row">
            <div class="col-7">
        <a href="{% url 'map:map-scrap-detail' id=m.pk %}" class="btn btn-outline-dart btn-block btn-sm btn-primary">view more</a>
    </div>
    <div style="font-size:20px; color:steelblue; text-decoration:none;"  class="col-5">

 
</div></div>
      </div>
    </div>
    {% endfor %}
  </div>

{% endblock %}

accounts/templates/accounts/my_food.html
{% extends 'base.html' %}


{% block title %}여기에 제목을 써주세요{% endblock %}

{% block content %}
{% include 'accounts/community_nav.html' %}
<script>
    let nav=document.getElementById("food");
    nav.style.fontSize="30px";
    // nav.style.color=blue;
    nav.style.color = 'steelblue';
</script>
<div class="row">
    {% for m in posts %}
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">

                <h1 class="card-title">{{m.title}}
                    
                </h1>
            </div>


   
          
        <a  href="{% url 'community:food-detail' m.pk %}" class="btn btn-outline-dart btn-block btn-sm btn-primary m-3">view more</a>
   
    <div style="font-size:20px; color:steelblue; text-decoration:none;"  class="col-5">

 </div>
      </div>
    </div>
    {% endfor %}
  </div>

{% endblock %}

accounts/templates/accounts/my_ott.html
{% extends 'base.html' %}


{% block title %}여기에 제목을 써주세요{% endblock %}

{% block content %}
{% include 'accounts/community_nav.html' %}
<script>
    let nav=document.getElementById("ott");
    nav.style.fontSize="30px";
    // nav.style.color=blue;
    nav.style.color = 'steelblue';
</script>
<div class="row">
    {% for m in posts %}
    <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
    
                    <h1 class="card-title">{{m.title}}
                        
                    </h1>
                </div>
    
    
       
              
            <a  href="{% url 'community:delivery-detail' m.pk %}" class="btn btn-outline-dart btn-block btn-sm btn-primary m-3">view more</a>
       
        <div style="font-size:20px; color:steelblue; text-decoration:none;"  class="col-5">
    
     </div>
          </div>
        </div>
    {% endfor %}
  </div>

{% endblock %}

accounts/templates/accounts/my_trade.html
{% extends 'base.html' %}


{% block title %}여기에 제목을 써주세요{% endblock %}


{% block content %}
<a href="{% url 'accounts:mypage' %}"><button type="button" class="btn-close m-2" aria-label="Close"></button></a>

<div class="container">
    <div class="row justify-content-center">
      <!-- 중고거래 물품 업로드 카드 -->
      {% for post in trades %}
          <div class="card mx-3 mb-3" style="width: 18rem;">
            {% if post.head_image %}
              <img src="{{ post.head_image.url }}" height="200px" class="card-img-top">
            {% else %}

            {% endif %}
            <div class="card-body">
              <h5 class="card-title">{{ post.title }}</h5>
              <p class="card-text">{{ post.body }}</p>
              <a href="{% url 'accounts:my-trade-detail' post_id=post.pk %}" class="btn btn-primary">view more</a>
            </div>
          </div>
          {% empty %}
            <span class="m-3">올린 중고 상품이 없습니다.</span>
      {% endfor %}
      
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/mypage.html
{% extends 'base.html' %}


{% block title %}마이페이지{% endblock %}

{% block content %}
<h2 class="mt-3">
  <span style="background-color: aliceblue; border-radius: 10px;" class="mt-4">회원정보</span>
</h2><div class="card mb-3" >
    <a style="text-decoration: none" href="{% url 'accounts:logout' %}">
    <div style="color:black" class="card-body">
      로그아웃
    </div>
</a>
</div>
<div class="card mb-3">
    <a style="text-decoration: none" href="{% url 'accounts:update-user-info' %}">
    <div style="color:black" class="card-body">
      회원정보 수정
    </div>
</a>
  </div>
  <h2 class="mt-3">
  <span style="background-color: aliceblue; border-radius: 10px;" class="mt-4">중고거래</span>
</h2>
  <div class="card mb-3">
    <a style="text-decoration: none" href="{% url 'trade:liked_posts' %}">
    <div style="color:black" class="card-body">
      내가 찜한 중고상품
    </div>
</a>
  </div>

  <div class="card mb-3">
    <a style="text-decoration: none" href="{% url 'accounts:my-trade' %}">
    <div style="color:black" class="card-body">
      내가 올린 중고상품
    </div>
  </a>
  </div>

  <div class="card mb-3">
    <a style="text-decoration: none" href="{% url 'accounts:review-list' %}">
    <div style="color:black" class="card-body">
      작성할 수 있는 리뷰 목록 보기
    </div>
  </a>
  </div>
  
  <div class="card mb-3">
    <a style="text-decoration: none" href="{% url 'accounts:proceeding-chat' %}">
    <div style="color:black" class="card-body">
      요청한 채팅보기
    </div>
  </a>
  </div>
  <h2 class="mt-3">
  <span style="background-color: aliceblue; border-radius: 10px;" class="mt-4">제휴</span>
</h2>
  <div class="card mb-3">
  <a style="text-decoration: none" href="{% url 'accounts:map-scrap' %}">
  <div style="color:black" class="card-body">
    스크랩한 제휴 정보
  </div>
</a>
</div>

<h2 class="mt-3">
  <span style="background-color: aliceblue; border-radius: 10px;" class="mt-4">커뮤니티</span>
</h2>
  <div class="card mb-3">
  <a style="text-decoration: none" href="{% url 'accounts:my-post-food' %}">
  <div style="color:black" class="card-body">
    내가 쓴 글
  </div>
</a>
</div>

{% endblock %}

accounts/templates/accounts/review_list.html
{% extends 'base.html' %}


{% block title %}여기에 제목을 써주세요{% endblock %}

{% block content %}
<a href="{% url 'accounts:mypage' %}"><button type="button" class="btn-close m-2" aria-label="Close"></button></a>

{% for p in posts %}

<div class="card mb-1">
    <div style="color:black" class="card-body">
        <a style="text-decoration: none" href="{% url 'trade:trade_detail' p.id %}">상품-{{p.title}}<br>
        판매자 - {{p.author.nickname}}</a>
    </div>
    {% for review in p.post_review.all %}
    {% if review.reviewer.id == request.user.id %}
    <button type="button" class="btn btn-outline-primary m-3">이미 작성함</button>
{% endif %}
  {% endfor %}
  
 
  </div>
  

{% endfor %}

{% endblock %}

accounts/templates/accounts/seller_chat.html
{% extends 'base.html' %}


{% block title %}여기에 제목을 써주세요{% endblock %}

{% block content %}

<a href="{% url 'accounts:mypage' %}"><button type="button" class="btn-close m-2" aria-label="Close"></button></a>

{% for c in chat_room %}

<div class="card mb-3">
    <a style="text-decoration: none" href="{% url 'trade:chating' c.post.id  c.id %}">
    <div style="color:black" class="card-body">
        사려는 물건-{{c.post.title}}<br>
        사려는사람 - {{c.buyer.nickname}}</a>
    </div>
  </a>
  </div>

{% endfor %}

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}회원가입{% endblock %}

{% block content %}
<div style="text-align: center;">
<form action="" method="POST" enctype="multipart/form-data" id="signupForm">
    {% csrf_token %}
    <div class="input-group my-3">
        <span class="input-group-text"> 아이디  </span>
        {{ form.username|add_class:"form-control" }}
        {% if form.username.errors %}
        <script>
          alert("{{ form.username.errors.as_text }}");
      </script>
        {% endif %}
    </div>
    <div class="input-group my-3">
        <span class="input-group-text"> 닉네임  </span>
        {{ form.nickname|add_class:"form-control" }}
        {% if form.nickname.errors %}
        <script>
          alert("{{ form.nickname.errors.as_text }}");
      </script>
        {% endif %}
    </div>
    <div class="input-group my-3">
        <span class="input-group-text"> 프로필 사진  </span>
        {{ form.profile|add_class:"form-control" }}
        {% if form.profile.errors %}
        <script>
          alert("{{ form.profile.errors.as_text }}");
      </script>
        {% endif %}
    </div>
    <div class="input-group my-3">
        <span class="input-group-text"> 이메일  </span>
        {{ form.email|add_class:"form-control" }}
        {% if form.email.errors %}
        <script>
          alert("{{ form.email.errors.as_text }}");
      </script>
      {% endif %}
    </div>
    <div class="input-group my-3">
        <span class="input-group-text"> 비밀번호   </span>
        {{ form.password1|add_class:"form-control" }}
        {% if form.password1.errors %}
        <script>
          alert("{{ form.password1.errors.as_text }}");
      </script>
        {% endif %}
    </div>
    <div class="input-group my-3">
        <span class="input-group-text"> 비밀번호 확인  </span>
        {{ form.password2|add_class:"form-control" }}
        {% if form.password2.errors %}
        <script>
          alert("{{ form.password2.errors.as_text }}");
      </script>
        {% endif %}
    </div>

    <div class="my-5" style="text-align: center;">
        <button type="submit" class="btn btn-lg btn-primary" id="btn">회원가입</button>
    </div>

</form>


</div>
<div style="text-align: center;">
    이미 계정이 있으신가요?<br>
    <a href="{% url 'accounts:login' %}">로그인</a>하러가기
</div>
{% endblock %}

accounts/templates/accounts/trade_detail.html
{% extends 'base.html' %}

{% block title %}Product Detail{% endblock %}

{% block content %}

<div class="container">

  <div class="card mx-auto mt-3" style="width: 18rem;">
    <a href="{% url 'accounts:my-trade' %}"><button type="button" class="btn-close m-2" aria-label="Close"></button></a>

    {% if post.head_image %}
      <img src="{{ post.head_image.url }}" height="200px" class="card-img-top">
  
    {% endif %}
    <div class="card-body">
      <h5 class="card-title">{{ post.title }}</h5>
      <p class="card-text">{{ post.body }}</p>
      <p class="card-text">Price: {{ post.price }}</p>

      <a href="{% url 'trade:edit_post' pk=post.pk %}" class="btn btn-warning mb-2">글 수정</a>

      <!-- 삭제 버튼 -->
      <form method="post" action="{% url 'trade:delete_post' pk=post.pk %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger mb-2">글 삭제</button>
      </form>
        <button class=" btn btn-primary">
          <a style="color:white; text-decoration: none;" href="{% url 'accounts:seller-chat' post.id  %}">
            열린 채팅방 보기
          </a>
        </button>
 

    </div>
  </div>
</div>

{% endblock %}