accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns=[
    path('signup/',signup_view, name='signup'),
    path('login/',login_view,name='login' ),
    path('logout/',logout_view, name='logout'),
    path('mypage/',mypage,name="mypage"),
    path('update-user-info/',update_userinfo, name='update-user-info'),
    path('my-benefit-scrap',benefit_scrap, name='benefit-scrap'),
    path('my-map-scrap',map_scrap, name='map-scrap'),
    path('my-trade',my_trade, name='my-trade'),
    path('my-trade-detail/<int:post_id>/',my_trade_detail, name='my-trade-detail'),
    path('chatroom/<int:post_id>/',seller_chat, name='seller-chat'),
    path('proceeding-chat',proceeding_chat, name='proceeding-chat'),
    path('leave-chat-room/<int:room_id>/',leave_chat_room, name='leave-chat-room'),
    path('review-list/',review_make, name='review-list'),
    path('my-post-food/',my_post_food, name='my-post-food'),
    path('my-post-ott/',my_post_ott, name='my-post-ott'),
]

alchanso/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',include('main_page.urls')),
    path('trade/',include('trade.urls', namespace='trade')),
    path('',include('main.urls')),
    path('map/',include('map.urls',namespace='map')),
    path('community/',include('community.urls',namespace='community')),
    path('consumption/',include('consumption.urls',namespace='consumption')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
]+ static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

community/yourprojectname/yourprojectname/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

map/urls.py
from django.urls import path
from .views import *

app_name='map'

urlpatterns=[
    path('',map_benefit_list, name='map-benefit'),
    path('map-detail/<int:pk>/',map_detail.as_view(), name='map-detail'),
    path('benefit-detail/<int:pk>/', benefit_detail.as_view(), name='benefit-detail'),
    path('scrap-benefit/<int:id>/',benefit_scrap, name='benefit-scrap'),
    path('scrap-map/<int:id>/',map_scrap, name='map-scrap'),
    path('mypage/benefit-detail/<int:id>/',benefit_scrap_detail, name='benefit-scrap-detail'),
    path('mypage/map-detail/<int:id>/',map_scrap_detail, name='map-scrap-detail'),
    
]

trade/urls.py
from django.urls import path
from . import views

app_name='trade'

urlpatterns=[
    path('r/',views.trade_require,name='trade'),
    path('f/',views.trade_finish, name='trade-finish'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.trade_detail, name='trade_detail'),
    path('<int:pk>/edit/', views.edit_post, name='edit_post'),
    path('<int:pk>/delete/', views.delete_post, name='delete_post'),
    path('<int:post_id>/chat/<int:chatroom_id>', views.into_chatroom, name='chating'),
    path('<int:post_id>/go-chat/',views.chat, name='go-chat'),
    path('seller-chat/',views.seller_chat, name="seller-chat"),
    path('<int:pk>/chat/', views.chat, name='chat'),
    path('<int:pk>/like/', views.like_post, name='like_post'),
    path('liked/', views.liked_posts, name='liked_posts'),
    path('<int:post_id>/review/', views.create_review, name='review'),
]

trade/models.py
from django.db import models
from users.models import User


class Post(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()
    price = models.CharField(max_length=50)
    head_image = models.ImageField(upload_to='trade/images/%Y/%m/%d/', blank=True)
    place = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    likes = models.ManyToManyField(User, related_name='liked_posts', blank=True)
    allowed_reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='allowed_reviews')

    def __str__(self):
        return f'[{self.pk}]{self.title}'
    def get_absolute_url(self):
        return f'/trade/{self.pk}/'

class ChatRoom(models.Model):
    post=models.ForeignKey(Post, related_name="chat", on_delete=models.CASCADE)
    buyer=models.ForeignKey(User, related_name='buyer',on_delete=models.CASCADE)
    seller=models.ForeignKey(User, related_name='seller',on_delete=models.CASCADE)

class Chatting(models.Model):
    chat_room=models.ForeignKey(ChatRoom, related_name="chat_room", on_delete=models.CASCADE )
    text=models.CharField(max_length=100)
    writer=models.ForeignKey(User, related_name='chatting_writer',on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)

class Review(models.Model):
    post = models.ForeignKey('Post', related_name='post_review', on_delete=models.CASCADE)
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    rating = models.PositiveIntegerField(default=5)  # 1에서 5까지의 평가를 가정합니다.
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.reviewer}님의 {self.post.title}에 대한 후기'

trade/forms.py
from django import forms
from .models import Post, Review


class PostForm(forms.ModelForm):
    allowed_reviewer_text = forms.CharField(required=False)
    class Meta:
        model=Post
        fields=('title', 'body', 'head_image', 'price', 'place', 'allowed_reviewer_text')
        labels = {
            'title': '제목 ',
            'body': '자세한 설명 ',
            'price': '가격 ',
            'head_image': '사진 첨부 ',
            'place': '만날 장소 ',
            'allowed_reviewer': '후기 작성 대상 닉네임',
        }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating']
        labels = {
            'rating': '평가',
        }

trade/views.py
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Chatting, ChatRoom, Review
from .forms import PostForm, ReviewForm
from users.models import User

def trade_require(request):
    posts = Post.objects.filter(allowed_reviewer__isnull=True).order_by('-created_at')
    return render(request, 'trade/trade_first.html', {'posts': posts})

def trade_finish(request):
    posts = Post.objects.filter(allowed_reviewer__isnull=False).order_by('-created_at')
    return render(request, 'trade/trade_finish.html', {'posts': posts})

def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('trade:trade')
    else:
        form = PostForm()
    return render(request, 'trade/trade_write.html', {'form': form})

def trade_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    find_review=Review.objects.filter(post=post,reviewer=request.user )

    # 이미 후기가 존재한다면 후기를 남기지 못하도록 한정
    review_exists = find_review.exists()
    return render(request, 'trade/trade_detail.html', {'post': post,'review_exists':review_exists})

def delete_post(request, pk):
    record=get_object_or_404(Post, pk=pk)
    record.delete()
    return redirect('trade:trade')

def edit_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    # 현재 사용자가 글의 작성자인지 확인
    if request.user != post.author:
        return render(request, '403.html', status=403)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            allowed_reviewer_text = form.cleaned_data.get('allowed_reviewer_text')
            post.allowed_reviewer = User.objects.filter(nickname=allowed_reviewer_text).first()

            form.save()
            return redirect('trade:trade_detail', pk=pk)
    else:
        form = PostForm(instance=post)

    return render(request, 'trade/trade_write.html', {'form': form})

def create_review(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
   

    if request.method == 'POST':
        form = ReviewForm(request.POST)
                
        if form.is_valid():
            review = form.save(commit=False)
            review.post = post
            review.reviewer = request.user
            # 전체 리뷰 수 증가
            post.author.review_count+=1

            post.author.save()
            # 평점 계산
            post.author.grade=(post.author.grade*(post.author.review_count-1)+review.rating)/post.author.review_count
            review.save()
            post.author.save()
            return redirect('trade:trade_detail', pk=post_id)
    else:
        form = ReviewForm()

    return render(request, 'trade/review.html', {'form': form,'post':post})

def chat(request, pk):
    post = get_object_or_404(Post, pk=pk)
    # 처음 열었을 경우는 저장, 아니면 그냥 값 들고옴 
    chat_room, created=ChatRoom.objects.get_or_create(
        buyer=request.user,
        seller=post.author,
        post=post
    )
    return redirect('trade:chating',pk, chat_room.id)


def chat(request, post_id):
    post=get_object_or_404(Post, pk=post_id)
    # 처음 열었을 경우는 저장, 아니면 그냥 값 들고옴 
    chat_room, created = ChatRoom.objects.get_or_create(
        buyer=request.user,
        seller=post.author,
        post=post
    )
    return redirect('trade:chating', post_id, chat_room.id)

# 채팅방으로 들어감
def into_chatroom(request, post_id, chatroom_id):
    chat_room=get_object_or_404(ChatRoom, id=chatroom_id)

    if request.method == "POST":
        text = request.POST['text']
        Chatting.objects.create(
            text=text,
            chat_room=chat_room,
            writer=request.user
        )
        return redirect('trade:chating', post_id=post_id, chatroom_id=chatroom_id)

    chats=Chatting.objects.filter(chat_room=chat_room)
    return render(request, 'trade/chat.html', {'chats': chats})

# 판매자가 채팅 조회
def seller_chat(request):
    chat_room=ChatRoom.objects.filter(seller=request.user)
    return render(request, 'trade/seller_chat.html',{'chat_room':chat_room})


    return render(request, 'trade/trade_chat.html', {'post': post})

# 찜하기 
def like_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.user in post.likes.all():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)

    return redirect('trade:trade_detail', pk=pk)

def liked_posts(request):
    liked_posts = request.user.liked_posts.all()
    return render(request, 'trade/liked_posts.html', {'liked_posts': liked_posts})

trade/templates/trade/chat.html
{% extends 'base.html' %}

{% block title %}채팅방{% endblock %}

{% block content %}
<style>
    .container-xl{
        height:10px;
    }
    .footer{
        display:none;
    }
    .chat-container {
        width: 100%;
        height: 700px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 10px;
        background-color: #f9f9f9;
        display: flex;
        flex-direction: column;
    }

    .message-container {
        display: flex;
        flex-direction: column;
        max-width: 100%;
        height: calc(100% - 60px);
        overflow-y: auto;
        margin-bottom: 10px;
    }

    .message {
        max-width: 70%;
        word-break: break-word;
        margin-bottom: 10px;
    }

    .sender,
    .receiver {
        padding: 10px;
        border-radius: 8px;
    }

    .sender {
        background-color: #f8f5c6;
        text-align: right;
        align-self: flex-end; 
    }

    .receiver {
        background-color: rgb(221, 237, 240);
        text-align: left;
        align-self: flex-start; 
    }

    .input-container {
        display: flex;
    }

    .input-field {
        flex: 1;
        padding: 5px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .send-button {
        padding: 5px;
        background-color: steelblue;
        color: white;
        border: none;
        border-radius: 5px;
    }
</style>


<div class="chat-container">
    <div class="message-container" id="message-container">
        {% for c in chats %}
            <div class="message {% if request.user == c.writer %}sender{% else %}receiver{% endif %}">
                <div>
                    {{ c.text }}<br>
                    <small style="margin:0px; font-size: 10px;">작성자 : {{ c.writer.username }} - {{ c.created_at }}</small>
                </div>
            </div>
        {% endfor %}
    </div>

    <form method="POST" class="input-container">
        {% csrf_token %}
        <input
            name="text"
            type="text"
            class="input-field"
            id="dynamic-input-field"
            oninput="updateChatContainerSize(this)"
        />
        <button type="submit" class="send-button">Send</button>
    </form>

    <script>
        // 페이지 로딩 시 자동으로 입력창에 포커스 설정
        window.onload = function() {
            document.getElementById('dynamic-input-field').focus();
            updateChatContainerSize(document.getElementById('dynamic-input-field'));
        };

        window.addEventListener('resize', function() {
            updateChatContainerSize(document.getElementById('dynamic-input-field'));
        });

        function updateChatContainerSize(input) {
            var messageContainer = document.getElementById('message-container');
            messageContainer.scrollTop = messageContainer.scrollHeight;

            // 항상 채팅 입력창이 보이도록 처리
            input.scrollIntoView();
        }
    </script>
</div>
{% endblock %}

trade/templates/trade/liked_posts.html
{% extends 'base.html' %}

{% block title %}Liked Posts{% endblock %}

{% block content %}
<a href="{% url 'accounts:mypage' %}"><button type="button" class="btn-close m-2" aria-label="Close"></button></a>

<div class="container">
    <h2>찜한 물품</h2>

    {% if liked_posts %}
        <div class="row">
            {% for post in liked_posts %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <!-- 만약 글쓴이가 후기 작성자를 정했다면 [판매완료]가 뜨도록 -->
                        {% if post.allowed_reviewer %}
                        <br><h3 style="text-align: center;"><strong>[판매완료]</strong></h3>
                        {% endif %}
                        {% if post.head_image %}
                        <img src="{{ post.head_image.url }}" class="card-img-top" alt="Product Image">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <p class="card-text">{{ post.body }}</p>
                            <p class="card-text">Price: {{ post.price }}</p>
                            <a href="{% url 'trade:trade_detail' pk=post.pk %}" class="btn btn-primary">상세 보기</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>찜한 물품이 없습니다.</p>
    {% endif %}
</div>
{% endblock %}

trade/templates/trade/review.html
{% extends 'base.html' %}

{% block title %}후기 작성{% endblock %}

{% block content %}
<style>
  .star {
    transition: transform 0.2s ease-in-out, box-shadow 0.2s ease-in-out;
  }

  .shake {
    animation: shake 0.5s ease-in-out;
  }

  @keyframes shake {
    0%, 100% {
      transform: translateX(0);
    }
    25% {
      transform: translateX(-5px);
    }
    50% {
      transform: translateX(5px);
    }
    75% {
      transform: translateX(-5px);
    }
  }
</style>

<div class="container my-3">
  <div class="card text-center">
    <div class="card-header">
      <h2>후기 작성</h2>
    </div>
    <div class="card-body">
      <h4 class="card-title">상품명 : {{post.title}}</h4>
      <p class="card-text">판매자 : {{post.author}}</p>

      <form id="reviewForm" method="post">
        {% csrf_token %}

        <div style="font-size: 30px; color:steelblue" class="rating">
          <span class="star" data-value="1">☆</span>
          <span class="star" data-value="2">☆</span>
          <span class="star" data-value="3">☆</span>
          <span class="star" data-value="4">☆</span>
          <span class="star" data-value="5">☆</span>
        </div>

        <input type="hidden" id="ratingInput" name="rating" value="0">  <!-- 선택된 별의 개수를 저장할 hidden input -->

        <button type="submit" class="btn btn-primary my-3">리뷰 등록하기</button>
      </form>
    </div>
  </div>
</div>

<script>
  const stars = document.querySelectorAll('.star');
  const ratingInput = document.getElementById('ratingInput');

  stars.forEach((star) => {
    star.addEventListener('mouseenter', () => {
      const value = star.getAttribute('data-value');
      updateStars(value);
      star.classList.add('shake');
    });

    star.addEventListener('animationend', () => {
      star.classList.remove('shake');
    });

    star.addEventListener('mouseleave', () => {
      const value = ratingInput.value;
      updateStars(value);
    });

    star.addEventListener('click', () => {
      const value = star.getAttribute('data-value');
      ratingInput.value = value;
    });
  });

  function updateStars(value) {
    stars.forEach((star) => {
      if (star.getAttribute('data-value') <= value) {
        star.innerHTML = '★';
        star.style.color = 'steelblue';  // 수정된 부분
        star.style.cursor = 'pointer';  // 마우스를 올렸을 때 선택 모양으로 변경
        star.style.transform = 'scale(2)';  // 크기 확대
      } else {
        star.innerHTML = '☆';
        star.style.backgroundColor = '';  // 기본 배경색으로 복원
        star.style.cursor = '';  // 기본 커서로 복원
        star.style.transform = 'scale(1)';  // 크기 원래대로
        star.style.boxShadow = 'none';  // 그림자 제거
      }
    });
  }
</script>
{% endblock %}

trade/templates/trade/seller_chat.html
{% for c in chat_room %}
<a href="{% url 'trade:chating' c.post.id  c.id %}"><br><br><br>
    사려는 물건-{{c.post.title}}<br>
사려는사람 - {{c.buyer}}</a>
{% endfor %}

trade/templates/trade/trade_detail.html
{% extends 'base.html' %}

{% block title %}Product Detail{% endblock %}

{% block content %}

<a href="{% url 'trade:trade' %}"><button type="button" class="btn-close m-2" aria-label="Close"></button></a>

<div class="container">
  <div class="card mx-auto mt-5" style="width: 18rem;">
    <!-- 만약 글쓴이가 후기 작성자를 정했다면 [판매완료]가 뜨도록 -->
    {% if post.allowed_reviewer %}
    <br><h3 style="text-align: center;"><strong>[판매완료]</strong></h3><br>
    {% endif %}

    {% if post.head_image %}
      <img src="{{ post.head_image.url }}" height="200px" class="card-img-top">
    {% endif %}
    <div class="card-body">

        <h5 class="card-title"><strong>{{ post.title }}</strong></h5>
      <p class="card-text">{{ post.body }}</p>
      <p class="card-text">가격 : {{ post.price }}</p>
      <p class="card-text">만날 장소 : {{ post.place }}</p>
      <p class="card-text">판매자 : {{ post.author }} 평점 {{post.author.grade|floatformat:1}}</p>

      <!-- 수정 버튼 -->
      {% if request.user == post.author %}
        <a href="{% url 'trade:edit_post' pk=post.pk %}" class="btn btn-warning mb-2">글 수정</a>

        <!-- 삭제 버튼 -->
        <form method="post" action="{% url 'trade:delete_post' pk=post.pk %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger mb-2">글 삭제</button>
        </form>

      {% endif %}

      <!-- 찜하기 버튼 및 채팅하기 버튼 표시 -->
      {% if not post.allowed_reviewer and request.user != post.author %}
        <div class="btn-group">
          <form method="post" action="{% url 'trade:like_post' pk=post.pk %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-success mb-2">
              {% if request.user in post.likes.all %}
                취소하기
              {% else %}
                찜하기
              {% endif %}
            </button>
          </form>
        </div>

        <a href="{% url 'trade:go-chat' post_id=post.pk %}" class="btn btn-primary mb-2">채팅하기</a>
      {% endif %}

      <!-- 후기 작성 버튼-->
      {% if request.user == post.allowed_reviewer %}

        <!-- 후기를 작성했다면 더이상 등록하지 못하도록 -->
        {% if not review_exists %}
          <a href="{% url 'trade:review' post_id=post.pk %}" class="btn btn-success mb-2">후기 작성</a>
        {% else %}
          <p>이미 작성된 후기입니다</p>
        {% endif %}
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

trade/templates/trade/trade_finish.html
{% extends 'base.html' %}

{% block title %}Trade{% endblock %}

{% block content %}

<div class="container">
  <div class="row justify-content-center">
    {% include 'trade/trade_nav.html' %}
    <!-- 중고거래 물품 업로드 카드 -->
    {% for post in posts %}
        <div class="card mx-3 mb-3" style="width: 18rem;">

          <!-- 만약 글쓴이가 후기 작성자를 정했다면 [판매완료]가 뜨도록 -->
          {% if post.allowed_reviewer %}
          <br><h3><strong>[판매완료]</strong></h3><br>
          {% endif %}

          {% if post.head_image %}
            <img src="{{ post.head_image.url }}" class="card-img-top">

          {% endif %}

          <div class="card-body">
            <h5 class="card-title"><strong>{{ post.title }}</strong></h5>
            <p class="card-text">{{ post.body }}</p>
            <a href="{% url 'trade:trade_detail' pk=post.pk %}" class="btn btn-primary">상세 보기</a>
          </div>
        </div>
        {% empty %}
        <div class="mt-5">
        올라온 중고거래가 없습니다
        </div>
    {% endfor %}
  </div>
</div>

<!--글쓰기 버튼 고정-->
<div id="write-button" style="position: fixed; bottom: 20px; right: 20px;">
  <a class="my-5" style="text-align:center;" href="{% url 'trade:create' %}">
    <button type="submit" class="btn btn-lg btn-primary">글쓰기</button>
  </a>
</div>
</div>
<script>
  let nav=document.getElementById("finish");
  nav.style.fontSize="30px";
  // nav.style.color=blue;
  nav.style.color = 'steelblue';
</script>
{% endblock %}

trade/templates/trade/trade_first.html
{% extends 'base.html' %}

{% block title %}Trade{% endblock %}

{% block content %}

<div class="container">
  <div class="row justify-content-center">
    <!-- 중고거래 물품 업로드 카드 -->
    {% for post in posts %}
        <div class="card mx-3 mb-3" style="width: 18rem;">

          <!-- 만약 글쓴이가 후기 작성자를 정했다면 [판매완료]가 뜨도록 -->
          {% if post.allowed_reviewer %}
          <br><h3><strong>[판매완료]</strong></h3><br>
          {% endif %}

          {% if post.head_image %}
            <img src="{{ post.head_image.url }}" class="card-img-top">

          {% endif %}

          <div class="card-body">
            <h5 class="card-title"><strong>{{ post.title }}</strong></h5>
            <p class="card-text">{{ post.body }}</p>
            <a href="{% url 'trade:trade_detail' pk=post.pk %}" class="btn btn-primary">상세 보기</a>
          </div>
        </div>
        {% empty %}
        <div class="mt-5">
        올라온 중고거래가 없습니다
        </div>
    {% endfor %}
  </div>
</div>

<!--글쓰기 버튼 고정-->
<div id="write-button" style="position: fixed; bottom: 20px; right: 20px;">
  <a class="my-5" style="text-align:center;" href="{% url 'trade:create' %}">
    <button type="submit" class="btn btn-lg btn-primary">글쓰기</button>
  </a>
</div>
</div>

{% endblock %}

trade/templates/trade/trade_nav.html
<nav class="mx-5 navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-nav  mx-5 ">
        <a class="nav-link" href="{% url 'trade:trade' %}" style="font-size: 16px;" id="selling">판매중</a>
    </div>

    <div class="navbar-nav  mx-5 ">
        <a class="nav-link" href="{% url 'trade:trade-finish' %}" style="font-size: 16px;" id="finish">판매완료</a>
    </div>
</nav>

trade/templates/trade/trade_write.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}중고거래 물품 글쓰기{% endblock %}

{% block content %}
    <h3>글쓰기</h3>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input-group my-3">
            <span class="input-group-text"> 제목  </span>
            {{ form.title|add_class:"form-control" }}
            {% if form.title.errors %}
            <script>
              alert("{{ form.title.errors.as_text }}");
          </script>
            {% endif %}
        </div>
        <div class="input-group my-3">
            <span class="input-group-text"> 상세설명  </span>
            {{ form.body|add_class:"form-control" }}
            {% if form.body.errors %}
            <script>
              alert("{{ form.body.errors.as_text }}");
          </script>
            {% endif %}
        </div>
        <div class="input-group my-3">
            <span class="input-group-text"> 이미지  </span>
            {{ form.head_image|add_class:"form-control" }}
            {% if form.head_image.errors %}
            <script>
              alert("{{ form.head_image.errors.as_text }}");
          </script>
            {% endif %}
        </div>
        <div class="input-group my-3">
            <span class="input-group-text"> 가격  </span>
            {{ form.price|add_class:"form-control" }}
            {% if form.price.errors %}
            <script>
              alert("{{ form.price.errors.as_text }}");
          </script>
            {% endif %}
        </div>
        <div class="input-group my-3">
            <span class="input-group-text"> 만날 장소  </span>
            {{ form.place|add_class:"form-control" }}
            {% if form.place.errors %}
            <script>
              alert("{{ form.place.errors.as_text }}");
          </script>
            {% endif %}
        </div>
        <div class="input-group my-3">
            <span class="input-group-text"> 구매자 닉네임  </span>
            {{ form.allowed_reviewer_text|add_class:"form-control" }}
            {% if form.allowed_reviewer_text.errors %}
            <script>
              alert("{{ form.allowed_reviewer_text.errors.as_text }}");
          </script>
            {% endif %}
        </div>
        <button type="submit">글 등록하기</button>
    </form>
{% endblock %}